Enable `ruff` `flake8-errmsg` checks and apply fixes. This moves exception error messages to an `err` variable, to make tracebacks more readable:
Before (error message is partially repeated):
```
>>> pyrtl.Simulation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lauj/venv/pyrtlnet/lib/python3.12/site-packages/pyrtl/simulation.py", line 126, in __init__
    tracer = SimulationTrace()
             ^^^^^^^^^^^^^^^^^
  File "/home/lauj/venv/pyrtlnet/lib/python3.12/site-packages/pyrtl/simulation.py", line 1490, in __init__
    raise PyrtlError("There needs to be at least one named non-constant wire "
pyrtl.pyrtlexceptions.PyrtlError: There needs to be at least one named non-constant wire for simulation to be useful
```

After (only one copy of the error message):
```
>>> pyrtl.Simulation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lauj/projects/pyrtl/pyrtl/simulation.py", line 143, in __init__
    tracer = SimulationTrace()
             ^^^^^^^^^^^^^^^^^
  File "/home/lauj/projects/pyrtl/pyrtl/simulation.py", line 1582, in __init__
    raise PyrtlError(msg)
pyrtl.pyrtlexceptions.PyrtlError: There needs to be at least one named non-constant wire for simulation to be useful
```