Fix pylint errors due to use of deprecated pyparsing methods.
pyrtl/importexport.py:191:27: E1121: Too many positional arguments for function call (too-many-function-args)
pyrtl/importexport.py:216:13: E1121: Too many positional arguments for method call (too-many-function-args)
pyrtl/importexport.py:216:13: E1123: Unexpected keyword argument 'parseAll' in method call (unexpected-keyword-arg)
pyrtl/importexport.py:512:17: E1133: Non-iterable value result is used in an iterating context (not-an-iterable)
pyrtl/importexport.py:1272:55: E1102: oneOf(gate_names) is not callable (not-callable)
pyrtl/importexport.py:1272:55: E1121: Too many positional arguments for function call (too-many-function-args)